[package]
name = "bookstore"
version = "0.1.0"
authors = ["Jack Wright <jack.wright@nike.com>"]

[[bin]]
name = "bookstore"
path = "src/main.rs"

[dependencies]
libc = "0.2.17"
time = "0.1.35"
regex = "0.2.1"
rusoto = {version = "0.23", features = ["dynamodb"]}
uuid = {version = "0.4.0", features = ["v4", "rustc-serialize"]}
router = "0.5.1"
hyper = "0.10"
rustc-serialize = "0.3.21"

[dependencies.iron]
version = "*"