[package]
name = "bookstore"
version = "0.1.0"
authors = ["Jack Wright <ayax79@gmail.com>"]

[[bin]]
name = "bookstore"
path = "src/main.rs"

[dependencies]
rocket = "0.3.6"
rocket_codegen = "0.3.6"
rocket_contrib = "0.3.6"

libc = "0.2.35"
time = "0.1.39"
regex = "0.2.5"
rusoto_core =  "0.31"
rusoto_dynamodb = "0.31"
uuid = {version = "0.4.0", features = ["v4", "rustc-serialize"]}
router = "0.5.1"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"