export OPENSSL_HOME="/usr/local/ssl"
#export DEP_OPENSSL_INCLUDE="$OPENSSL_HOME/include"
export OPENSSL_INCLUDE_DIR=$DEP_OPENSSL_INCLUDE
export OPENSSL_LIB_DIR="$OPENSSL_LIB_DIR/lib"
export OPENSSL_STATIC=true
export DYLD_LIBRARY_PATH="$OPENSSL_HOME/lib"
