---
apiVersion: v1
kind: Service
metadata:
  name: {{build.name}}
  {%- if "endpoint" in build.profile %}
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind: Mapping
      name: {{build.name}}-mapping
      prefix: {{build.profile.endpoint}}
      service: {{build.name}}
      {%- if "weight" in build.profile %}
      weight: {{build.profile.weight}}
      {%- endif %}
  {%- endif %}
spec:
  selector:
    app: {{build.name}}
  ports:
    - protocol: TCP
      port: 80
      targetPort: http-api
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{build.name}}
spec:
  selector:
    matchLabels:
      app: {{build.name}}
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{build.name}}
    spec:
      containers:
      - name: {{build.name}}
        image: {{build.images["Dockerfile"]}}
        imagePullPolicy: Always
        resources:
          requests:
            memory: 0.1G
            cpu: 0.1
          limits:
            memory: {{build.profile.max_memory}}
            cpu: {{build.profile.max_cpu}}
        ports:
          - name: http-api
            containerPort: 8080
        env:
          - name: BOOKSTORE_REDISPASSWORD
            valueFrom:
              secretKeyRef:
                name: ponderous-beetle-redis
                key: redis-password
          - name: BOOKSTORE_REDISHOST
            value: ponderous-beetle-redis-master.default.svc.cluster.local
          - name: BOOKSTORE_REDISPORT
            value: "6379"